<?php $designConfig = $this -> designConfig(); ?>
<?php if ($designConfig -> meta -> xml_doctype_header -> enabled): ?>
    <?= $this -> xmlDeclaration() . PHP_EOL ?>
<?php endif; ?>
<?= $this -> doctype($designConfig -> html -> doctype) . PHP_EOL ?>
<html lang="en">
<head>
    <?= $this -> headTitle() . PHP_EOL ?>
    <?= $this -> headMeta() . PHP_EOL ?>
    <?= $this -> headLink() . PHP_EOL ?>
    <?= $this -> addIeElements() . PHP_EOL ?>
    <?= $this -> headScript() . PHP_EOL; ?>
    <?= $this -> jsLocalStorage(); ?>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
    <div class="container">
        <div class="navbar-header">
        </div>
    </div>
</nav>
<div class="container">
    <?= $this -> content . PHP_EOL ?>
</div>
</body>
</html>
